#!/bin/sh

uci set smartdns.@smartdns[0].ipv6_server='0'
uci commit smartdns

  date=`date +%Y.%m.%d`	
  sed -i '/DISTRIB_REVISION/d' /etc/openwrt_release	
  echo "DISTRIB_REVISION='$date'" >> /etc/openwrt_release
  sed -i '/DISTRIB_DESCRIPTION/d' /etc/openwrt_release
  echo "DISTRIB_DESCRIPTION='OpenWrt Build By JarodChang'" >> /etc/openwrt_release

if [ ! -f /etc/config/placeholder ]; then
  uci set luci.main.lang=zh_cn
  uci set luci.main.mediaurlbase=/luci-static/atmaterial_ci
  uci commit luci

  uci set system.@system[0].timezone=CST-8
  uci set system.@system[0].zonename=Asia/Shanghai
  uci commit system

  uci set fstab.@global[0].anon_mount=1
  uci commit fstab
  sed -i 's/root:.*/root:$1$tTPCBw1t$ldzfp37h5lSpO9VXk4uUE\/:18336:0:99999:7:::/g' /etc/shadow
  uci set network.lan.ipaddr="192.168.0.250"
  uci set network.wan.proto=pppoe
  uci commit network
   
  sed -i '/ipv6.conf/d' /etc/sysctl.conf
  echo net.ipv6.conf.all.disable_ipv6=1 >> /etc/sysctl.conf
  echo net.ipv6.conf.default.disable_ipv6=1 >> /etc/sysctl.conf
  echo net.ipv6.conf.lo.disable_ipv6 = 1 >> /etc/sysctl.conf

  uci set smartdns.@smartdns[0].enabled='0'
  uci set smartdns.@smartdns[0].port='6053'
  uci set smartdns.@smartdns[0].redirect='none'
  uci set smartdns.@smartdns[0].tcp_server='1'
  uci set smartdns.@smartdns[0].prefetch_domain='1'
  uci set smartdns.@smartdns[0].serve_expired='1'
  uci set smartdns.@smartdns[0].server_name 'China'
  uci set smartdns.@smartdns[0].seconddns_port '7913'
  uci set smartdns.@smartdns[0].seconddns_tcp_server '1'
  uci set smartdns.@smartdns[0].seconddns_server_group 'World'
  uci set smartdns.@smartdns[0].seconddns_no_speed_check '1'
  uci set smartdns.@smartdns[0].seconddns_no_rule_nameserver '0'
  uci set smartdns.@smartdns[0].seconddns_no_rule_ipset '0'
  uci set smartdns.@smartdns[0].seconddns_no_rule_soa '0'
  uci set smartdns.@smartdns[0].seconddns_no_dualstack_selection '1'
  uci set smartdns.@smartdns[0].seconddns_no_cache '1'
  uci set smartdns.@smartdns[0].force_aaaa_soa '0'
  uci set smartdns.@smartdns[0].coredump '0'
  uci commit smartdns
  

[ -f "/etc/config/smartdns" ] && {
cat >> /etc/config/smartdns <<EOF
config server
	option name 'Tencent'
	option type 'udp'
	option enabled '1'
	option ip '119.29.29.29'
	option server_group 'China'
	option blacklist_ip '0'
config server
	option name 'AliDns'
	option type 'udp'
	option enabled '1'
	option ip '223.5.5.5'
	option server_group 'China'
	option blacklist_ip '0'
config server
	option name '114'
	option type 'tcp'
	option enabled '1'
	option ip '114.114.114.114'
	option server_group 'China'
	option blacklist_ip '0'
config server
	option name 'Cloudflare'
	option ip '1.1.1.1'
	option type 'tls'
	option enabled '1'
	option blacklist_ip '0'
	option server_group 'World'
config server
	option name 'OpenDns'
	option ip '208.67.222.222'
	option port '5353'
	option type 'tcp'
	option enabled '1'
	option server_group 'World'
	option blacklist_ip '0'
config server
	option name 'Google'
	option ip 'dns.google'
	option type 'tls'
	option enabled '1'
	option server_group 'World'
	option blacklist_ip '0'
config server
	option name 'IBM'
	option ip 'dns.quad9.net'
	option type 'tls'
	option enabled '1'
	option server_group 'World'
	option blacklist_ip '0'
config server
	option type 'tcp'
	option enabled '1'
	option ip '210.0.255.250'
	option blacklist_ip '0'
	option name 'HGC'
	option server_group 'World'
config server
	option type 'udp'
	option name 'Yinchuan'
	option ip '202.100.96.68'
	option server_group 'China'
	option blacklist_ip '0'
	option enabled '1'
config server
	option name 'Taiwan'
	option ip '168.95.1.1'
	option type 'tcp'
	option enabled '1'
	option server_group 'World'
	option blacklist_ip '0'
config server
	option type 'tcp'
	option ip '218.102.23.228'
	option blacklist_ip '0'
	option name 'PCCW'
	option server_group 'World'
	option enabled '1'
config server
	option name 'Macao'
	option ip '202.175.82.46'
	option type 'tcp'
	option enabled '1'
	option server_group 'World'
	option blacklist_ip '0'
config server
	option name 'RubyFish'
	option ip 'dns.rubyfish.cn'
	option type 'tls'
	option enabled '1'
	option server_group 'China'
	option blacklist_ip '0'
config server
	option enabled '1'
	option name 'Tsinghua'
	option ip '101.6.6.6'
	option port '5353'
	option type 'tcp'
	option blacklist_ip '0'
	option server_group 'China'
config server
	option enabled '1'
	option type 'udp'
	option name 'Baidu'
	option ip '180.76.76.76'
	option server_group 'China'
	option blacklist_ip '0'
config server
	option enabled '1'
	option name 'Yandex'
	option ip '77.88.8.8'
	option type 'tcp'
	option server_group 'World'
	option blacklist_ip '0'
config server
	option enabled '1'
	option name 'TaiWan Quad101'
	option ip '101.101.101.101'
	option type 'tls'
	option server_group 'World'
	option blacklist_ip '0'
EOF
}
fi

rm -rf /tmp/luci-modulecache/
rm -f /tmp/luci-indexcache

exit 0
